### ISSUE TITLE
Incompatibility with new store.wapt.fr packages

### ISSUE THREAD

**Issue by jf-guillou** [tranquilit/WAPT-archives#27]
Current stable version of wapt (1.3.13.0) doesn't handle properly .wapt packages built with newer versions.

Error traceback
```
KeyError: "There is no item named u'WAPT/manifest.sha1' in the archive"
Traceback (most recent call last):
  File "c:\wapt\waptservice\waptservice.py", line 2100, in run
    self.running_task.run()
  File "c:\wapt\waptservice\waptservice.py", line 1360, in pwrapper
    return func(*arg, **kwargs)
  File "c:\wapt\waptservice\waptservice.py", line 1420, in run
    self._run()
  File "c:\wapt\waptservice\waptservice.py", line 1822, in _run
    self.result = self.wapt.install(self.packagename,force = self.force)
  File "c:\wapt\common.py", line 4100, in install
    manifest_content = waptfile.open(u'WAPT/manifest.sha1').read()
  File "c:\wapt\lib\zipfile.py", line 964, in open
    zinfo = self.getinfo(name)
  File "c:\wapt\lib\zipfile.py", line 912, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named u'WAPT/manifest.sha1' in the archive"
```

This causes updates to fail when using raw new packages from https://store.wapt.fr/

Exemple :
Working : https://store.wapt.fr/package_details?package=tis-thunderbird_52.2.0-15_all.wapt
Broken package : https://store.wapt.fr/package_details?package=tis-thunderbird_52.3.0-17_all.wapt

Probable culprit : https://github.com/tranquilit/WAPT/commit/3a5fd7b7194aca564c8a6ad293edec7991d7f51d

Based on these facts, I would assume the tis- packages are now build using 1.5.x version. This is pretty problematic, since we can't use them directly anymore.

Is there a way to add a compatibility mode, like :
- Add both .sha1 and .sha256 signatures in new packages ?
- Release a 1.3.x client capable of handling .sha256 signatures ?
- 1.5.x release coming really soon ? (this could also break installs with older packages, since 1.5.x doesn't seem to handle .sha1 signatures anymore)

**Comment by htouvet** [comment]
Thanks for this.
You are true, we have moved to sha256 to comply with security agencies requirements.
The hashed of files, hash of manifest and hash of control's attributes (in 1.5, the control attributes are signed too) are now sha256.

We have added a compatibility mode in wapt 1.5.0.13 (july 12 2017) to be able to dual sign the packages.
But as our managed customers are all using 1.5, and as the dual signing was not mandatory, some packages are not properly signed.

We check and resign broken packages.

wapt 1.5 should be released end of september but will need on your side some adjustments.
In particular, 1.5 introduces : 
- postgresql database for wapt status and inventory. We have replaced mongo DB by Postgresql which is more natural to query for most users than a no sql database.
- websockets : waptservice http port 8088 listen only on loopback.  Adhoc action from waptconsole to hosts are tunneled through a websocket connection initiated bu hosts. This removes potential attack surface on hosts, and allow hosts behind NAT to be managed even if they are not directly visible from IP point of view from waptserver;
- signed actions : update / upgrade / install / remove adhoc actions initiated from waptconsole to hosts are signed with key as well as the packages. We don't rely on proper firewall configuration of hosts anymore.
- sha256 signatures
- https ssl certificate checking is enabled by default, so the deployment of a CA bundle for wapt is recommended, unless certificate check is explicitely disabled.

**Comment by htouvet** [comment]
Actually, on sept. 13,  A number of packages have been "dual" resigned with both sha1 and sha256 signatures, but package build nr has not been incremented :

 tis-flashplayer_27.0.0.130-2_all.wapt
 tis-adobeair_27.0.0.124-1_all.wapt
 tis-seafile_6.1.0-14_all.wapt
 tis-notepadplusplus_7.5.1-8_all.wapt
 tis-virtualbox_5.1.26-19_all.wapt
 tis-sweethome3d_5.5-3_all.wapt
 tis-7zip2_9.20.0.0-2_all.wapt
 tis-adobereader_2017.12.20098-2_all.wapt
 tis-audacity_2.1.3-2_all.wapt
 tis-bd-studio-pratic_1.0.5.0-3_all.wapt
 tis-chrome_61.0.3163.79-2_all.wapt
 tis-classicshell_4.3.1-3_all.wapt
 tis-config-for-firefox_4_all.wapt
 tis-disable-adminshare_1.0.0-1_all.wapt
 tis-disable-autoruns_1.0.0-1_all.wapt
 tis-disable-hiberboot_54_all.wapt
 tis-disable-hibernation_1.0-3_all.wapt
 tis-disable-netbios_4_all.wapt
 tis-disable-usbstorage_1.0.0-1_all.wapt
 tis-firefox_55.0-104_all.wapt
 tis-firefox_55.0.1-106_all.wapt
 tis-firefox_55.0.2-109_all.wapt
 tis-firefox-en_55.0.1-78_all.wapt
 tis-firefox-en_55.0.2-80_all.wapt
 tis-firefox-en_55.0-76_all.wapt
 tis-firefox-esr_52.3.0-17_all.wapt
 tis-firefox-esr-en_52.3.0-15_all.wapt
 tis-flashplayer_26.0.0.151-2_all.wapt
 tis-fusioninventory_2.3.21-2_all.wapt
 tis-geogebra_5.0.385.0-1_all.wapt
 tis-googleearth_7.3.0.3832-1_all.wapt
 tis-handbrake_1.0.7-1_all.wapt
 tis-java8_8.144-1_all.wapt
 tis-libreoffice_101_all.wapt
 tis-libreoffice-evolution_5.4.1.2-31_all.wapt
 tis-libreoffice-stable_5.3.6.1-31_all.wapt
 tis-ms-pstools_2.44-2_all.wapt
 tis-skype_7.40.32.103-14_all.wapt
 tis-spark_2.6.3-9_all.wapt
 tis-teamviewer_12.0.83369.0-1_all.wapt
 tis-thunderbird_52.3.0-17_all.wapt
 tis-winscp_5.11-1_all.wapt
